import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
  NavigationMenuMainLink,
} from "@/components/ui/navigation-menu";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "stardust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} default-background`}>
        <NavigationMenu className="fixed left-1/2 top-12 -translate-x-1/2 rounded-full">
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuMainLink href="/">Apps</NavigationMenuMainLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavigationMenuMainLink href="/about">
                Settings
              </NavigationMenuMainLink>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
        {children}
      </body>
    </html>
  );
}
